// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-k0iHH-4bHgKaqJJG9TRWaoKTb5ffueo',
    appId: '1:789928959183:web:642a78166d33b97d512bba',
    messagingSenderId: '789928959183',
    projectId: 'try-firebase-store',
    authDomain: 'try-firebase-store.firebaseapp.com',
    storageBucket: 'try-firebase-store.appspot.com',
    measurementId: 'G-D23J3WLP8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy_4PlNH4Bl0_loaL4x-uocd98MxcwDjY',
    appId: '1:789928959183:android:4329edae7fa81842512bba',
    messagingSenderId: '789928959183',
    projectId: 'try-firebase-store',
    storageBucket: 'try-firebase-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMFO-5Hg6ujDDvi2mJleIi3UTSm_b5E_Y',
    appId: '1:789928959183:ios:c607f99787bd8ddc512bba',
    messagingSenderId: '789928959183',
    projectId: 'try-firebase-store',
    storageBucket: 'try-firebase-store.appspot.com',
    iosClientId: '789928959183-e0t862ojar19pgulcnbm1hkr9b8t0a33.apps.googleusercontent.com',
    iosBundleId: 'com.example.tryFirebaseStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMFO-5Hg6ujDDvi2mJleIi3UTSm_b5E_Y',
    appId: '1:789928959183:ios:c607f99787bd8ddc512bba',
    messagingSenderId: '789928959183',
    projectId: 'try-firebase-store',
    storageBucket: 'try-firebase-store.appspot.com',
    iosClientId: '789928959183-e0t862ojar19pgulcnbm1hkr9b8t0a33.apps.googleusercontent.com',
    iosBundleId: 'com.example.tryFirebaseStore',
  );
}
